fix: don't send command complete on stream batch error (#656)
Also includes a minor fix where error is sent to the client in case of
portal exec instead of closing the connection.

```
glaredb=> select * from always_errors;
ERROR:  External error: Arrow error: External error: Execution error: always error
glaredb=>
```

Fixes #483

Signed-off-by: Vaibhav <vrongmeal@gmail.com>