fix: Error instead of panic when converting pg timestamps to arrow (#2430)
```
> select * from pg.public.comments;
Error: External error: External error: Overflow converting '0001-01-01 00:00:00 UTC' to Timestamp(Nanosecond, Some("UTC"))
```

Fixes: #2412

Signed-off-by: Vaibhav <vrongmeal@gmail.com>