fix: Return better error when querying pg table that doesn't exist (#1544)
Before:

> ERROR: Error during planning: Unable to fetch table provider for 'external_db.public.doesnotexist': Failed to dispatch to table: Failed to connect to Postgres instance: query returned an unexpected number of rows

After:

> ERROR: Error during planning: Unable to fetch table provider for 'external_db.public.doesnotexist': Failed to dispatch to table: Failed to query Postgres: failed to find table: 'public.doesnotexist'